version: '3.7'

services:
  mongo:
    restart: always
    image: mongo:${SERVICE_MONGO_VERSION}
    ports:
      - ${SERVICE_MONGO_HOST}:${SERVICE_MONGO_PORT}:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${SERVICE_MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${SERVICE_MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${SERVICE_MONGO_DB}
    volumes:
      - type: bind
        source: ${SERVICE_DATA}/data
        target: /data/db

services:
  postgres:
    restart: always
    image: postgres:${SERVICE_POSTGRES_VERSION}
    ports:
      - ${SERVICE_POSTGRES_HOST}:${SERVICE_POSTGRES_PORT}:5432
    environment:
      TZ: Asia/Shanghai
      POSTGRES_USER: ${SERVICE_POSTGRES_USER}
      POSTGRES_PASSWORD: ${SERVICE_POSTGRES_PASSWORD}
      POSTGRES_DB: ${SERVICE_POSTGRES_DB}
    volumes:
      - ${SERVICE_DATA}:/var/lib/postgresql/data


networks:
  default:
    external: true
    name: compose-ingress
