version: '3.7'

services:
  mongo:
    restart: always
    image: mongo:${SERVICE_MONGO_VERSION}
    ports:
      - ${SERVICE_MONGO_HOST}:${SERVICE_MONGO_PORT}:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${SERVICE_MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${SERVICE_MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${SERVICE_MONGO_DB}
    volumes:
      - type: bind
        source: ${SERVICE_DATA}/data
        target: /data/db

networks:
  default:
    external: true
    name: compose-ingress
